Feature users config ssh #9
stationgroup/ansible-experiments pull request #10
Opened 2018-08-19 19:13 UTC by srgvg

This is so far we got with your request. This one was somehow a bit more subjective, so we're not so sure this is exactly what you requested.
Please review this and let us know what you think.
Thanks, Serge & Vincent.

2018-08-20 18:54 UTC, reelsense commented
I'm looking through the documentation you guys produced. I haven't even tested it yet, but I'm really excited.

2018-08-23 22:02 UTC, reelsense requested changes
>This PR is fantastic. Despite the subjectivity of this project you did everything exactly how I wanted. I really appreciate how well you guys read my mind. Every time I thought I had a question, I thought _"I should see if they explain this is the documentation before I ask them..."_ sure enough, the doc had the answer or referenced the solution.
>
>I'm really grateful.

I posted an update on the original issue with a change. https://github.com/stationgroup/ansible-experiments/issues/9#issuecomment-415582205

As well as some question in the form of code comments; which can be seen in the PR: https://github.com/stationgroup/ansible-experiments/pull/10

2018-08-23 22:02 UTC, reelsense commented on add-users-groups-authorized_keys-dot-files/group_vars/all
> +    state: present
`TASK [users : Ensure .ssh folder is created]` fails if user is set to `absent` after it was previously `present`.
<details>
  <summary>(Click to expand code)</summary>

```yaml
TASK [users : Ensure .ssh folder is created] *******************************************************
failed: [127.0.0.1] (item={u'bash_lines': [{u'line': u'testline', u'state': u'present'}, {u'line': u'export SSH_AUTH_SOCK=$HOME/.gnupg/S.gpg-agent.ssh', u'state': u'present'}, {u'line': u"alias ls='ls lah'", u'state': u'present'}], u'name': u'remember', u'keys': [{u'state': u'present', u'file': u'key1'}], u'ssh_config': [{u'ServerAliveInterval': 10}], u'state': u'absent', u'groups': [u'mygroup'], u'uid': 1100}) => {
    "changed": false, 
    "gid": 1100, 
    "group": "1100", 
    "item": {
        "bash_lines": [
            {
                "line": "testline", 
                "state": "present"
            }, 
            {
                "line": "export SSH_AUTH_SOCK=$HOME/.gnupg/S.gpg-agent.ssh", 
                "state": "present"
            }, 
            {
                "line": "alias ls='ls lah'", 
                "state": "present"
            }
        ], 
        "groups": [
            "mygroup"
        ], 
        "keys": [
            {
                "file": "key1", 
                "state": "present"
            }
        ], 
        "name": "remember", 
        "ssh_config": [
            {
                "ServerAliveInterval": 10
            }
        ], 
        "state": "absent", 
        "uid": 1100
    }, 
    "mode": "0700", 
    "owner": "1100", 
    "path": "/home/remember/.ssh", 
    "size": 4096, 
    "state": "directory", 
    "uid": 1100
}

MSG:

chown failed: failed to look up user remember

ok: [127.0.0.1] => (item={u'keys': [{u'state': u'absent', u'file': u'key2'}], u'name': u'test', u'csh_lines': [{u'line': u'alias ls ls -lah', u'state': u'present'}]})

PLAY RECAP *****************************************************************************************
127.0.0.1                  : ok=8    changed=1    unreachable=0    failed=1   
```

</details>

2018-08-23 22:02 UTC, reelsense commented on add-users-groups-authorized_keys-dot-files/group_vars/all
> +    state: present
I guess the procedure I should use is. When a user is removed. Remove their variables so the script continues to function. Because the variables try to set because the home folder exists even though the user is gone.

2018-08-23 22:02 UTC, reelsense commented on add-users-groups-authorized_keys-dot-files/group_vars/all
> +      - mygroup
If I add a user to a group: `admin`. I can't remove the user from a group. **Please advise** if there is a method I've over looked.

2018-08-23 22:02 UTC, reelsense commented on add-users-groups-authorized_keys-dot-files/group_vars/all
> +      - line: "alias ls='ls lah'"
I can add but not remove, multiline bash entries.

```yaml
users:
  - name: remember
    state: present
    groups:
      - mygroup
    uid: 1100
    keys:
      - file: key1
        state: present
    bash_lines:
      - line: "testline"
        state: absent
      - line: "export SSH_AUTH_SOCK=$HOME/.gnupg/S.gpg-agent.ssh"
        state: present
      - line: "alias ls='ls -lah'"
        state: present
      - line: |
         #this is a testline
         #this is a testline2
        state: absent
    ssh_config:
      - ServerAliveInterval: 10
```

2018-08-23 22:02 UTC, reelsense commented on add-users-groups-authorized_keys-dot-files/group_vars/all
> +      - line: "alias ls='ls lah'"
**Please advise**.

2018-08-26 11:50 UTC, vincentvdk commented on add-users-groups-authorized_keys-dot-files/group_vars/all
> +    state: present
We'll have to make the 'users.state' variable required. I'll make the necessary changes to the tasks and check for required variables at runtime.

2018-08-26 13:15 UTC, vincentvdk commented on add-users-groups-authorized_keys-dot-files/group_vars/all
> +      - mygroup
the 'user' module ws using the 'append' option. This will be removed

2018-08-26 13:16 UTC, vincentvdk commented on add-users-groups-authorized_keys-dot-files/group_vars/all
> +      - line: "alias ls='ls lah'"
I updated the playbooks to add a task for multi line content leveraging the 'blockinfile' module.

2018-08-26 13:16 UTC, vincentvdk commented on add-users-groups-authorized_keys-dot-files/group_vars/all
> +      - line: "alias ls='ls lah'"
I made the necessary changes and commited everything to @srgvg his repository so he can make a proper PR here.

2018-08-30 08:23 UTC, srgvg commented
I added @vincentvdk's most recent commit addressing the requested changes, https://github.com/stationgroup/ansible-experiments/pull/10/commits/59749462c0eb66f9dc53744d8e45fffcbd202a5e to this PR.

2018-08-30 19:01 UTC, reelsense commented
Thank you.

I'll try to test it this weekend. If I cant test it this weekend I'll probably be to busy to test for a while, and I'll just have you bill me. I don't want to make you wait too much longer.

2018-08-30 19:07 UTC, reelsense commented on add-users-groups-authorized_keys-dot-files/roles/users/tasks/users.yml
> +  portinstall:
I'm going to try this with [`pkgng`](https://docs.ansible.com/ansible/2.6/modules/pkgng_module.html?highlight=pkg) I don't like to mix _ports_ in with my _pkg's_ if I can avoid it.

2018-09-01 01:05 UTC, reelsense approved these changes

2018-09-02 06:45 UTC, merged